#=========================================================================
# Extract spice from GDS using magic
#=========================================================================
# Author : Kartik Prabhu
# Date   : May 21, 2021
#

name: open-magic-gds2spice

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------
inputs:
  - adk
  - design.gds.gz

outputs:
  - design_extracted.spice

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined

commands:
  - cp -L inputs/design.gds.gz design.gds.gz 
  - gunzip design.gds.gz
  - cp inputs/adk/magicrc .magicrc
  - envsubst < extract.tcl.template > extract.tcl
  - magic -noconsole -dnull extract.tcl | tee gds2spice.log
  - mv {design_name}.spice outputs/design_extracted.spice
